## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spotify_lyrics}
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-dll: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

genius:
  api:
    token: DFnGiiGzLyEYS7mIQU22G_8Oq0mQAhvQ3oPKQuk2DW1RmEzljsbpMLBcXlG2F1Xs
    url: https://api.genius.com
    endpoints:
      search: /search
